#!/usr/bin/env python3
from __future__ import annotations

import os
import subprocess
import sys
from typing import NoReturn


def main() -> NoReturn:
    cfg = ('git', 'config')
    name = subprocess.check_output((*cfg, 'user.name')).decode().strip()
    email = subprocess.check_output((*cfg, 'user.email')).decode().strip()
    interactive = '-ti' if sys.stdin.isatty() else '-i'

    cmd = (
        'docker', 'run', '--rm', interactive,
        '--env', f'GIT_AUTHOR_NAME={name}',
        '--env', f'GIT_AUTHOR_EMAIL={email}',
        '--env', f'GIT_COMMITTER_NAME={name}',
        '--env', f'GIT_COMMITTER_EMAIL={email}',
        '--env', f'DEBFULLNAME={os.environ["DEBFULLNANME"]}',
        '--env', f'DEBEMAIL={os.environ["DEBEMAIL"]}',
        *sys.argv[1:],
    )
    os.execvp(cmd[0], cmd)


if __name__ == '__main__':
    raise SystemExit(main())
