#!/usr/bin/env python3
from __future__ import annotations

import os
import subprocess
import sys
from typing import NoReturn


def _git_cfg(s: str) -> str:
    cmd = ('git', 'config', s)
    return subprocess.check_output(cmd).decode().strip()


def main() -> NoReturn:
    name = _git_cfg('user.name')
    email = _git_cfg('user.email')
    interactive = '-ti' if sys.stdin.isatty() else '-i'

    cmd = (
        'docker', 'run', '--rm', interactive,
        '--env', f'GIT_AUTHOR_NAME={name}',
        '--env', f'GIT_AUTHOR_EMAIL={email}',
        '--env', f'GIT_COMMITTER_NAME={name}',
        '--env', f'GIT_COMMITTER_EMAIL={email}',
        '--env', f'DEBFULLNAME={name}',
        '--env', f'DEBEMAIL={email}',
        *sys.argv[1:],
    )
    os.execvp(cmd[0], cmd)


if __name__ == '__main__':
    raise SystemExit(main())
