#!/usr/bin/env python3
import argparse
import os.path
import subprocess
from typing import NoReturn

HERE = os.path.abspath(os.path.dirname(__file__))
IMG = 'deadsnakes/deadsnakes-gbp'


def main() -> NoReturn:
    parser = argparse.ArgumentParser()
    parser.add_argument('-v', '--volume', dest='volumes', action='append')
    args, rest = parser.parse_known_args()

    # pristine-tar on bionic is too new for xenial
    subprocess.check_call((os.path.join(HERE, 'pull-image'), IMG))

    gitconfig = os.path.expanduser('~/.gitconfig')
    cmd = (
        'docker', 'run', '--rm', '-ti',
        '--volume', f'{gitconfig}:/homedir/.gitconfig:ro',
        '--volume', f'{os.getcwd()}:/tmp/src:rw',
        '--user', f'{os.getuid()}:{os.getgid()}',
        *(f'--volume={volume}' for volume in args.volumes),
        IMG, 'gbp', *rest,
    )
    os.execvp(cmd[0], cmd)


if __name__ == '__main__':
    exit(main())
