#!/usr/bin/env python3
import argparse
import os.path
import subprocess
from typing import NoReturn

HERE = os.path.abspath(os.path.dirname(__file__))
IMG = 'docker.io/deadsnakes/deadsnakes-gbp'


def main() -> NoReturn:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--container-engine', choices=['docker', 'podman'], default='docker',
        help='Linux containers runner (default: %(default)s)',
    )
    parser.add_argument('-v', '--volume', dest='volumes', action='append')
    args, rest = parser.parse_known_args()

    # TODO: pristine-tar on bionic is too new for xenial
    subprocess.check_call((os.path.join(HERE, 'pull-image'), IMG))

    gitconfig = os.path.expanduser('~/.gitconfig')
    cmd = (
        args.container_engine, 'run', '--rm', '-ti',
        '--volume', f'{gitconfig}:/homedir/.gitconfig:ro',
        '--volume', f'{os.getcwd()}:/tmp/src:rw',
        *(f'--volume={volume}' for volume in args.volumes),
        IMG, 'gbp', *rest,
    )
    os.execvp(cmd[0], cmd)


if __name__ == '__main__':
    raise SystemExit(main())
