#!/usr/bin/env python3
import argparse
import subprocess


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('image')
    args = parser.parse_args()

    # if it already exists, skip pulling it
    if not subprocess.call(
            ('docker', 'image', 'inspect', args.image),
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    ):
        return 0

    return subprocess.call(('docker', 'pull', '-q', args.image))


if __name__ == '__main__':
    exit(main())
