#!/usr/bin/env python3
import argparse
import subprocess


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('image')
    parser.add_argument(
        '--container-engine', choices=['docker', 'podman'], default='docker',
        help='Linux containers runner (default: %(default)s)',
    )
    args = parser.parse_args()

    # if it already exists, skip pulling it
    if not subprocess.call(
            (args.container_engine, 'image', 'inspect', args.image),
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    ):
        return 0

    return subprocess.call((args.container_engine, 'pull', '-q', args.image))


if __name__ == '__main__':
    raise SystemExit(main())
