#!/usr/bin/env python3
from __future__ import annotations

import os.path
import subprocess

HERE = os.path.abspath(os.path.dirname(__file__))
TOOLS = os.path.join(HERE, 'tools')
BUILD = os.path.join(HERE, 'build')


def main() -> int:
    subprocess.check_call(('rm', '-rf', '../dist'))
    subprocess.check_call((BUILD, '--source'))

    subprocess.check_call((
        TOOLS, '--volume', f'{os.path.abspath("../dist")}:/dist:ro',
        'bash', '-euxc', 'cd /dist && dput ppa:deadsnakes/ppa *.changes',
    ))

    cmd = (TOOLS, 'dpkg-parsechangelog', '--show-field=version')
    version = subprocess.check_output(cmd).decode().strip().replace('~', '_')
    subprocess.check_call(('git', 'tag', f'debian/{version}'))
    subprocess.check_call(('git', 'push', 'origin', 'HEAD', '--tags'))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
