FROM ubuntu:bionic
RUN : \
    && apt-get update -qq \
    && DEBIAN_FRONTEND=noninteractive apt-get install \
        -qq -y --no-install-recommends \
        git-buildpackage \
        pristine-tar \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
ENV HOME=/homedir
WORKDIR /tmp/src
