FROM ubuntu:focal
RUN : \
    && apt-get update -qq \
    && DEBIAN_FRONTEND=noninteractive apt-get install \
        -qq -y --no-install-recommends \
        git-buildpackage \
        pristine-tar \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
ENV HOME=/homedir LANG=C.UTF-8
RUN git config --system --add safe.directory /tmp/src
WORKDIR /tmp/src
